exclude:
  - README.md
  - .gitignore
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title
baseurl: 

#prose
siteurl: 'http://jueyang.github.io'
relativeLinks: 'http://jueyang.github.io/starter/links.jsonp'
media: 'media'